---
- name: Download CockroachDB
  get_url:
    url: "https://binaries.cockroachdb.com/cockroach-v2.1.5.linux-amd64.tgz"
    dest: /tmp/cockroach-v2.1.5.linux-amd64.tgz

- name: Extract the CockroachDB
  unarchive:
    src: /tmp/cockroach-v2.1.5.linux-amd64.tgz
    dest: /tmp
    remote_src: yes

- name: Copy the binary
  command: cp -f /tmp/cockroach-v2.1.5.linux-amd64/cockroach /usr/local/bin

- name: Put systemd file
  copy:
    src: cockroachdb.service
    dest: /etc/systemd/system/cockroachdb.service
    
- name: Put SQL file
  copy:
    src: backup.sql
    dest: /tmp/backup.sql

- name: systemctl daemon-reload
  command: sudo systemctl daemon-reload
  
- name: Start CockroachDB
  command: sudo systemctl start cockroachdb


- name: Start sleep
  command: sleep 60s
  
- name: Created table CockroachDB
  shell: cockroach sql --insecure --host=0.0.0.0:26257 --execute="CREATE DATABASE IF NOT EXISTS testsystems;"
  
- name: Import CockroachDB
  shell: cockroach sql --insecure --user=root --host=0.0.0.0 --port=26257 --database=testsystems < /tmp/backup.sql
