---
- name: Download CockroachDB
  get_url:
    url: "https://binaries.cockroachdb.com/cockroach-v2.1.5.linux-amd64.tgz"
    dest: /tmp/cockroach-v2.1.5.linux-amd64.tgz

- name: Extract the CockroachDB
  unarchive:
    src: /tmp/cockroach-v2.1.5.linux-amd64.tgz
    dest: /tmp
    remote_src: yes

- name: Copy the binary
  command: cp -i /tmp/cockroach-v2.1.5.linux-amd64/cockroach /usr/local/bin

- name: Start CockroachDB
  command: nohup cockroach start  --insecure --host=localhost &
  
- name: Created table CockroachDB
  command: cockroach sql --insecure --host=localhost:26257 --execute="CREATE DATABASE IF NOT EXISTS testsystems;"
  
- name: Import CockroachDB
  command: cockroach sql --insecure --user=root --host=0.0.0.0 --port=26257 --database=testsystems < backup.sql
