---
- name: Install common packages
  hosts: swarm
  roles:
   - docker

- name: Configure Manager
  hosts: swarm-managers
  roles:
   - dockermanager

- name: Configure Workers
  hosts: swarm-workers
  roles:
   - dockerworker
