---
- name: register cocroachdb sercice with curl check
  consul:
    service_name: cocroachdb
    service_port: 8080
    script: curl http://{{ hostvars['CockroachDB'].ansible_ssh_host }}/
    interval: 60s
   	tags:
      - database

- name: register jenkins sercice with curl check
  consul:
    service_name: jenkins
    service_port: 8080
    script: curl http://{{ hostvars['jenkins'].ansible_ssh_host }}/
    interval: 60s
   	tags:
      - jenkins

- name: register app sercice with curl check
  consul:
    service_name: app
    service_port: 4580
    script: curl http://{{ hostvars[groups["swarm-managers"][0]]["inventory_hostname"] }}/
    interval: 60s
   	tags:
      - app

- name: register console sercice with curl check
  consul:
    service_name: docker-console
    service_port: 8080
    script: curl http://{{ hostvars[groups["swarm-managers"][0]]["inventory_hostname"] }}/console
    interval: 60s
   	tags:
      - docker
      - console

- name: register docker sercice with curl check
  consul:
    service_name: docker-master
    service_port: 80
    script: curl http://{{ hostvars[groups["swarm-managers"][0]]["inventory_hostname"] }}/
    interval: 60s
   	tags:
      - docker
      
- name: register docker-swarm sercice with curl check
  consul:
    service_name: docker-slave
    service_port: 81
    script: curl http://{{ hostvars[groups["swarm-workers"][0]]["inventory_hostname"] }}/
    interval: 60s
   	tags:
      - docker
