---
 - name: Consul servicse Template
   template:
     src: "service1.json.j2"
     dest: "/tmp/service_{{ item.name }}.json"
     owner: "root"
     group: "root"
     mode: 0777
   with_items:
    - { name: "cocroachdb",node: "cocroachdb", ip: "{{ hostvars['CockroachDB_host'].ansible_ssh_host }}", port: 8080, script: "health"}
 
 - name: Install consul module from curl
   shell: curl --request PUT --data @/tmp/service_{{ item.name }}.json http://localhost:8500/v1/catalog/register
   with_items:
    - { name: "cocroachdb", ip: "{{ hostvars['CockroachDB_host'].ansible_ssh_host }}", port: 8080, script: "health", "node": "cocroachdb"}

