---
  - name: Installing wget
    apt:
      name=wget state=present

  - name: Adding Jenkins APT-Key
    apt_key: url=https://pkg.jenkins.io/debian/jenkins-ci.org.key state=present

  - name: Creating jenkins.list
    shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    args:
      creates: /etc/apt/sources.list.d/jenkins.list

  - name: Installing jenkins
    apt:
      update_cache=yes
      name=jenkins state=present