---
- get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_archive }}"
    dest: "/tmp/{{ consul_archive }}"

- unarchive:
    src: "/tmp/{{ consul_archive }}"
    dest: /opt/consul/bin
    copy: no

- file:
    state: link
    src: /opt/consul/bin/consul
    dest: /usr/local/bin/consul
    force: yes

- name: create dir
  command: mkdir /etc/consul

- name: Find my public ip
  uri: 
   url: http://ifconfig.me/ip
   return_content: yes
  register: ip_response

- name: Consul servicse Template
  template:
     src: "service1.json.j2"
     dest: "/etc/consul/install.json"
     owner: "root"
     group: "root"
     mode: 0777
  with_items:
          - { ip: "{{ hostvars['consul_host'].ansible_ssh_host }}" }



- name: Consul servicse Template
  template:
     src: "service.json.j2"
     dest: "/etc/systemd/system/consulagent.service"
     owner: "root"
     group: "root"
     mode: 0777
  with_items:
          - { ip: "{{ hostvars['consul_host'].ansible_ssh_host }}" }

- name: open port
  command: iptables -A INPUT -m state --state NEW -p tcp --dport 8301 -j ACCEPT

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  
- name: Start consul
  command: systemctl start consulagent
